// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID   int32
	Name string
}

type Card struct {
	ID    int32
	Value int32
	Suit  int32
	Art   string
}

type Chat struct {
	ID       int32
	Members  []int32
	Messages []int32
}

type Chatmessage struct {
	ID        int32
	Sender    int32
	Message   string
	Timestamp pgtype.Timestamptz
}

type Deck struct {
	ID    int32
	Cards []byte
}

type Gameplaycard struct {
	ID        int32
	Cardid    int32
	Origowner pgtype.Int4
	Currowner pgtype.Int4
	State     int32
}

type Match struct {
	ID                 int32
	Playerids          []int32
	Creationdate       pgtype.Timestamptz
	Privatematch       bool
	Elorangemin        int32
	Elorangemax        int32
	Deckid             pgtype.Numeric
	Cutgamecardid      int32
	Currentplayerturn  int32
	Turnpasstimestamps []string
	Gamestate          int32
	Art                string
}

type Matchhistory struct {
	ID                    int32
	Matchid               int32
	Matchcompletetiondate pgtype.Timestamptz
	Winners               []int32
	Losers                []int32
}

type Player struct {
	ID        int32
	Accountid int32
	Play      []int32
	Hand      []int32
	Kitty     []int32
	Score     int32
	Isready   bool
	Art       string
}
