@host = http://{{host}}:1323/v1
@p1accountId = 1
@p2accountId = 2
@matchId = 1
@cutIndex = 30

### Create new match and player
POST {{host}}/match/{{p1accountId}}
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### Game should be in New state
GET {{host}}/match/{{matchId}}
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Is GameState NewGameState", function () {
        client.log(jsonPath(response.body, "$.Gamestate",))
        client.assert(jsonPath(response.body, "$.Gamestate",) == "New", "GameState is not New");
    });
%}

### Get match deck
GET {{host}}/match/{{matchId}}/cards
	
> {%
    var matchIdToMatch = 1;   
    var minNumOfMatches = 52; 

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

     client.test(`At least ${minNumOfMatches} match(es) exists`, function () {
        client.assert(jsonPath(response.body, "@") >= `${minNumOfMatches}`, "Not enough matches");
    });
%}

### Get list of open matches
GET {{host}}/open

> {%
    var minNumOfMatches = 1;    

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

     client.test(`At least ${minNumOfMatches} match(es) exists`, function () {
        client.assert(jsonPath(response.body, "@",) >= `${minNumOfMatches}`, "Not enough matches");
    });
%}

### P2 join match
PUT {{host}}/match/{{matchId}}/join/{{p2accountId}}
Content-Type: application/json

> {%
    var matchIdToMatch = 1;    

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Is GameState Determine", function () {
        client.log(jsonPath(response.body, "$.Gamestate",))
        client.assert(jsonPath(response.body, "$.Gamestate",) == "Determine", "GameState is not CutState");
    });
%}

### Determine first player
PUT {{host}}/match/{{matchId}}/determinefirst
Content-Type: application/json
	
> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Current Player is player ID 1`, function () {
        client.assert(jsonPath(response.body, "$.Currentplayerturn") == `1`, "CurrentPlayerTurn is null");
    });
%}

### Deal cards to player
PUT {{host}}/match/{{matchId}}/deal
Content-Type: application/json
	
> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Current Player is player ID 1`, function () {
        client.assert(jsonPath(response.body, "$.Currentplayerturn") == `1`, "CurrentPlayerTurn is null");
    });
%}

### P1 discard to kitty
PUT {{host}}/match/{{matchId}}/player/{{p1accountId}}/kitty
Content-Type: application/json

{
  "cardIds": [
    1,2
  ],
  "senderId": 1
}

> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### P2 discard to kitty
PUT {{host}}/match/{{matchId}}/player/{{p1accountId}}/kitty
Content-Type: application/json

{
  "cardIds": [
    7,8
  ],
  "senderId": 2
}

> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### Count playre P1 Kitty
GET {{host}}/match/{{matchId}}/deck/kitty
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("P1 score is 0", function () {
        
        client.assert(jsonPath(response.body, "$.Cards.size()",) == "4", "There are too mant cards! " + jsonPath(response.body, "$.Cards.size()",));
    });
%}


### Cut match deck
PUT {{host}}/match/{{matchId}}/cut/{{cutIndex}}
Content-Type: application/json
	
> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Cutgamecardid is 30`, function () {
        client.assert(jsonPath(response.body, "$.Cutgamecardid") == `30`,"CurrentPlayerTurn is " + jsonPath(response.body, "$.Cutgamecardid"));
    });
%}  

### P1 play card and passes turn
PUT {{host}}/match/{{matchId}}/player/{{p1accountId}}/play 
Content-Type: application/json
	
> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Current Player Turn is player ID 2`, function () {
        client.assert(jsonPath(response.body, "$.Currentplayerturn") == `2`, "CurrentPlayerTurn is null");
    });

    client.test("Is GameState PassTurn", function () {
        client.log(jsonPath(response.body, "$.Gamestate",))
        client.assert(jsonPath(response.body, "$.Gamestate",) == "PassTurn", "GameState is not CutState");
    });
    
%}

### Player 1 should have score of 0
GET {{host}}/match/{{matchId}}
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("P1 score is 0", function () {
        
        client.assert(jsonPath(response.body, "$.Players[0].Score",) == "0", "GameState is not New");
    });
%}


### P2 play card and passes turn
PUT {{host}}/match/{{matchId}}/player/{{p2accountId}}/play 
Content-Type: application/json
	
> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Current Player Turn is player ID 1`, function () {
        client.assert(jsonPath(response.body, "$.Currentplayerturn") == `1`, "CurrentPlayerTurn is null");
    });

    client.test("Is GameState PassTurn", function () {
        client.log(jsonPath(response.body, "$.Gamestate",))
        client.assert(jsonPath(response.body, "$.Gamestate",) == "PassTurn", "GameState is not CutState");
    });
    
%}

## Count points in  play

### Player 2 should have score of 0
GET {{host}}/match/{{matchId}}
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("P1 score is 0", function () {
        
        client.assert(jsonPath(response.body, "$.Players[1].Score",) == "0", "GameState is not New");
    });
%}

##Count Kitty


### Count playre P1 Kitty
GET {{host}}/match/{{matchId}}/deck/kitty
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("P1 score is 0", function () {
        
        client.assert(jsonPath(response.body, "$.Cards.size()",) == "4", "There are too mant cards! " + jsonPath(response.body, "$.Cards.size()",));
    });
%}


### Return all cards to deck

PUT {{host}}/match/{{matchId}}/deck/shuffle
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("P1 score is 0", function () {
        client.assert(jsonPath(response.body, "$.Cards.size()",) == "52", "There are too mant cards! " + jsonPath(response.body, "$.Cards.size()",));
    });
%}


### Pass turn

PUT {{host}}/match/{{matchId}}/pass
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("P1 score is 0", function () {
       client.assert(jsonPath(response.body, "$.Gamestate",) == "Deal", "GameState is " + jsonPath(response.body, "$.Gamestate",));
    });
%}


### Deal cards to player
PUT {{host}}/match/{{matchId}}/deal
Content-Type: application/json
	
> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Current Player is player ID 2`, function () {
        client.assert(jsonPath(response.body, "$.Currentplayerturn") == `2`, "CurrentPlayerTurn is " + jsonPath(response.body, "$.Currentplayerturn"));
    });
%}

### P1 discard to kitty
PUT {{host}}/match/{{matchId}}/player/{{p1accountId}}/kitty
Content-Type: application/json

{
  "cardIds": [
    1,2
  ],
  "senderId": 1
}

> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

### P1 discard to kitty
PUT {{host}}/match/{{matchId}}/player/{{p1accountId}}/kitty
Content-Type: application/json

{
  "cardIds": [
    7,8
  ],
  "senderId": 2
}

> {%

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}