@host = http://{{host}}:1323/v1
@p1accountId = 1
@p2accountId = 2
@matchId = 1
@cutIndex = "30"

### Create new match and player
POST {{host}}/match/{{p1accountId}}
Content-Type: application/json

> {%
    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });
 
    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Is GameState NewGameState", function () {
        client.log(jsonPath(response.body, "$.GameState",))
        client.assert(jsonPath(response.body, "$.GameState",) == "NewGameState", "GameState is not NewGameState");
    });
%}

### Get list of open matches
GET {{host}}/open

> {%
    var minNumOfMatches = 1;    

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

     client.test(`At least ${minNumOfMatches} match(es) exists`, function () {
        client.assert(jsonPath(response.body, "@",) >= `${minNumOfMatches}`, "Not enough matches");
    });
%}

### Get match details by id
GET {{host}}/match/{{matchId}}

> {%
    var matchIdToMatch = 1;    

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Is Id ${matchIdToMatch}`, function () {
        client.assert(jsonPath(response.body, "$.MatchId",) == `${matchIdToMatch}`, "Id is wrong");
    });
%}

### p2 join match
PUT {{host}}/match/{{matchId}}/join/{{p2accountId}}
Content-Type: application/json

> {%
    var matchIdToMatch = 1;    

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Is Id ${matchIdToMatch}`, function () {
        client.assert(jsonPath(response.body, "$.ID",) == `${matchIdToMatch}`, "Id is wrong");
    });

    client.test("Is GameState CutState", function () {
        client.log(jsonPath(response.body, "$.Gamestate",))
        client.assert(jsonPath(response.body, "$.Gamestate",) == "CutState", "GameState is not CutState");
    });
%}

### Get match deck
GET {{host}}/match/{{matchId}}/cards
	
> {%
    var matchIdToMatch = 1;   
    var minNumOfMatches = 52; 

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

     client.test(`At least ${minNumOfMatches} match(es) exists`, function () {
        client.assert(jsonPath(response.body, "@",) >= `${minNumOfMatches}`, "Not enough matches");
    });
%}

### Cut match deck
PUT {{host}}/match/{{matchId}}/cut
Content-Type: application/json

{
  "MatchId": {{matchId}},
  "CutIndex": {{cutIndex}}
}
	
> {%
    var matchIdToMatch = 1;    

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test(`Is Id ${matchIdToMatch}`, function () {
        client.assert(response.body == 1, "Id is wrong");
    });

%}
