@host = http://{{host}}:1323/v1
@p1accountId = 1
@p2accountId = 2
@matchId = 1
@cutIndex = "30"

### Get list of open matches
GET {{host}}/open

> {%
    var minNumOfMatches = 1;    

    client.test("Test status code", function() {
        console.log("Response status: " + response.status);
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

     client.test(`At least ${minNumOfMatches} match(es) exists`, function () {
        client.assert(jsonPath(response.body, "@",) >= `${minNumOfMatches}`, "Not enough matches");
    });
%}