// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: account.sql

package queries

import (
	"context"
)

const getAccountForId = `-- name: GetAccountForId :one
SELECT account.id, account.name FROM account WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountForId(ctx context.Context, id int) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForId, id)
	var i Account
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
