// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForAddCardToDeck implements pgx.CopyFromSource.
type iteratorForAddCardToDeck struct {
	rows                 []AddCardToDeckParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddCardToDeck) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddCardToDeck) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Deckid,
		r.rows[0].Matchcardid,
	}, nil
}

func (r iteratorForAddCardToDeck) Err() error {
	return nil
}

func (q *Queries) AddCardToDeck(ctx context.Context, arg []AddCardToDeckParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"deck_matchcard"}, []string{"deckid", "matchcardid"}, &iteratorForAddCardToDeck{rows: arg})
}

// iteratorForCreateMatchCard implements pgx.CopyFromSource.
type iteratorForCreateMatchCard struct {
	rows                 []CreateMatchCardParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMatchCard) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMatchCard) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Cardid,
		r.rows[0].Origowner,
		r.rows[0].Currowner,
		r.rows[0].State,
	}, nil
}

func (r iteratorForCreateMatchCard) Err() error {
	return nil
}

func (q *Queries) CreateMatchCard(ctx context.Context, arg []CreateMatchCardParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"matchcard"}, []string{"cardid", "origowner", "currowner", "state"}, &iteratorForCreateMatchCard{rows: arg})
}
