CREATE TABLE IF NOT EXISTS deck (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cutMatchCardId integer,
  CONSTRAINT fk_matchCard
    FOREIGN KEY(cutMatchCardId) 
      REFERENCES matchCard(id)
);