CREATE TABLE IF NOT EXISTS matchCard (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cardId integer NOT NULL,
  CONSTRAINT fk_card
    FOREIGN KEY(cardId) 
      REFERENCES card(id),
  origOwner integer,
  CONSTRAINT fk_player
    FOREIGN KEY(origOwner) 
      REFERENCES player(id),
  currOwner integer,
    FOREIGN KEY(currOwner)
      REFERENCES player(id),
  state varchar(256) NOT NULL,
  deckId integer NOT NULL,
  CONSTRAINT fk_deck
    FOREIGN KEY(deckId) 
      REFERENCES deck(id)
);
