CREATE TABLE IF NOT EXISTS match (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  creationDate timestamptz NOT NULL DEFAULT now(),
  privateMatch boolean NOT NULL,
  eloRangeMin int NOT NULL,
  eloRangeMax int NOT NULL,
  cutGameCardId integer NOT NULL,
  dealerId integer,
  CONSTRAINT fk_dealer
    FOREIGN KEY(dealerId) 
      REFERENCES player(id),
  currentPlayerTurn integer,
  CONSTRAINT fk_player
    FOREIGN KEY(currentPlayerTurn) 
      REFERENCES player(id),
  turnPassTimestamps timestamptz [] NOT NULL,
  gameState varchar(256) NOT NULL,
  art varchar(256) NOT NULL
);
