CREATE TABLE IF NOT EXISTS deck (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cutMatchCardId integer,
  matchId integer NOT NULL,
  CONSTRAINT fk_match
    FOREIGN KEY(matchId) 
      REFERENCES match(id)
);
