CREATE TABLE IF NOT EXISTS player (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  accountId integer NOT NULL,
  CONSTRAINT fk_account
    FOREIGN KEY(accountId) 
      REFERENCES account(id),
  score integer NOT NULL,
  isReady boolean NOT NULL,
  art varchar(500) NOT NULL
);