// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/login/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "id to login with",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Account"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/card/": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Update card by id",
                "parameters": [
                    {
                        "description": "card Object to save",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/queries.Card"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Card"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Create new card",
                "parameters": [
                    {
                        "description": "card Object to save",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/queries.Card"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Card"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/admin/match/": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Get match by barcode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search for match by barcode",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Match"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/card/": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Get card by barcode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search for card by barcode",
                        "name": "barcode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Store in which the barcode was found",
                        "name": "storeId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Card"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/allcards/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Get all cards",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/queries.Card"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/gameplaycards/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Get cards by ids",
                "parameters": [
                    {
                        "type": "string",
                        "description": "csv of ids",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/queries.Card"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/kitty": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Update kitty with ids",
                "parameters": [
                    {
                        "description": "array of ids to add to kitty",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.HandModifier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Match"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/match/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Get match by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search for match by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.MatchDetailsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Update match by id",
                "parameters": [
                    {
                        "description": "match Object to update",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/queries.Match"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Match"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Create new match",
                "parameters": [
                    {
                        "description": "MatchRequirements",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.MatchRequirements"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/match/cards/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Get match cards by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search for match by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/queries.GetGameCardsForMatchRow"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    }
                }
            }
        },
        "/player/match/cut": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Cut deck by index",
                "parameters": [
                    {
                        "description": "Deck index that is to become the cut",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.CutDeckReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/match/deck/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deck"
                ],
                "summary": "Get deck by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search for deck by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.GameDeck"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    }
                }
            }
        },
        "/player/match/join": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Join match by id",
                "parameters": [
                    {
                        "description": "match Object to update",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.JoinMatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.MatchDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/matches/open": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Get match by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.GameMatch"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {}
                    }
                }
            }
        },
        "/player/play": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "summary": "Update play with ids",
                "parameters": [
                    {
                        "description": "array of ids to add to play",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.HandModifier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Match"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/player/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Get player by barcode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search for match by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Update player by barcode",
                "parameters": [
                    {
                        "description": "player Object to save",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/queries.Player"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Create new player",
                "parameters": [
                    {
                        "description": "player Object to save",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Get player by barcode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search for match by barcode",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/player/ready": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "players"
                ],
                "summary": "Update player to mark as ready",
                "parameters": [
                    {
                        "description": "player id to update",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "pgtype.InfinityModifier": {
            "type": "integer",
            "enum": [
                1,
                0,
                -1
            ],
            "x-enum-varnames": [
                "Infinity",
                "Finite",
                "NegativeInfinity"
            ]
        },
        "pgtype.Int4": {
            "type": "object",
            "properties": {
                "int32": {
                    "type": "integer"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "pgtype.Timestamptz": {
            "type": "object",
            "properties": {
                "infinityModifier": {
                    "$ref": "#/definitions/pgtype.InfinityModifier"
                },
                "time": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "queries.Account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "queries.Card": {
            "type": "object",
            "properties": {
                "art": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "suit": {
                    "$ref": "#/definitions/queries.Cardsuit"
                },
                "value": {
                    "$ref": "#/definitions/queries.Cardvalue"
                }
            }
        },
        "queries.Cardstate": {
            "type": "string",
            "enum": [
                "Deck",
                "Hand",
                "Play",
                "Kitty"
            ],
            "x-enum-varnames": [
                "CardstateDeck",
                "CardstateHand",
                "CardstatePlay",
                "CardstateKitty"
            ]
        },
        "queries.Cardsuit": {
            "type": "string",
            "enum": [
                "Spades",
                "Clubs",
                "Hearts",
                "Diamonds"
            ],
            "x-enum-varnames": [
                "CardsuitSpades",
                "CardsuitClubs",
                "CardsuitHearts",
                "CardsuitDiamonds"
            ]
        },
        "queries.Cardvalue": {
            "type": "string",
            "enum": [
                "Ace",
                "Two",
                "Three",
                "Four",
                "Five",
                "Six",
                "Seven",
                "Eight",
                "Nine",
                "Ten",
                "Jack",
                "Queen",
                "King",
                "Joker"
            ],
            "x-enum-varnames": [
                "CardvalueAce",
                "CardvalueTwo",
                "CardvalueThree",
                "CardvalueFour",
                "CardvalueFive",
                "CardvalueSix",
                "CardvalueSeven",
                "CardvalueEight",
                "CardvalueNine",
                "CardvalueTen",
                "CardvalueJack",
                "CardvalueQueen",
                "CardvalueKing",
                "CardvalueJoker"
            ]
        },
        "queries.Gamestate": {
            "type": "string",
            "enum": [
                "NewGameState",
                "JoinGameState",
                "WaitingState",
                "MatchReady",
                "DealState",
                "DiscardState",
                "CutState",
                "PlayState",
                "OpponentState",
                "KittyState",
                "GameWonState",
                "GameLostState",
                "MaxGameState"
            ],
            "x-enum-varnames": [
                "GamestateNewGameState",
                "GamestateJoinGameState",
                "GamestateWaitingState",
                "GamestateMatchReady",
                "GamestateDealState",
                "GamestateDiscardState",
                "GamestateCutState",
                "GamestatePlayState",
                "GamestateOpponentState",
                "GamestateKittyState",
                "GamestateGameWonState",
                "GamestateGameLostState",
                "GamestateMaxGameState"
            ]
        },
        "queries.GetGameCardsForMatchRow": {
            "type": "object",
            "properties": {
                "card": {
                    "$ref": "#/definitions/queries.Card"
                },
                "matchcard": {
                    "$ref": "#/definitions/queries.Matchcard"
                }
            }
        },
        "queries.Match": {
            "type": "object",
            "properties": {
                "art": {
                    "type": "string"
                },
                "creationdate": {
                    "$ref": "#/definitions/pgtype.Timestamptz"
                },
                "currentplayerturn": {
                    "type": "integer"
                },
                "cutgamecardid": {
                    "type": "integer"
                },
                "deckid": {
                    "type": "integer"
                },
                "elorangemax": {
                    "type": "integer"
                },
                "elorangemin": {
                    "type": "integer"
                },
                "gamestate": {
                    "$ref": "#/definitions/queries.Gamestate"
                },
                "id": {
                    "type": "integer"
                },
                "playerids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "privatematch": {
                    "type": "boolean"
                },
                "turnpasstimestamps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pgtype.Timestamptz"
                    }
                }
            }
        },
        "queries.Matchcard": {
            "type": "object",
            "properties": {
                "cardid": {
                    "type": "integer"
                },
                "currowner": {
                    "$ref": "#/definitions/pgtype.Int4"
                },
                "id": {
                    "type": "integer"
                },
                "matchID": {
                    "type": "integer"
                },
                "origowner": {
                    "$ref": "#/definitions/pgtype.Int4"
                },
                "state": {
                    "$ref": "#/definitions/queries.Cardstate"
                }
            }
        },
        "queries.Player": {
            "type": "object",
            "properties": {
                "accountid": {
                    "type": "integer"
                },
                "art": {
                    "type": "string"
                },
                "hand": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "isready": {
                    "type": "boolean"
                },
                "kitty": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "play": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "vo.CutDeckReq": {
            "type": "object",
            "properties": {
                "cutIndex": {
                    "type": "string"
                },
                "matchId": {
                    "type": "integer"
                },
                "playerId": {
                    "type": "integer"
                }
            }
        },
        "vo.GameDeck": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.GetGameCardsForMatchRow"
                    }
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "vo.GameMatch": {
            "type": "object",
            "properties": {
                "art": {
                    "type": "string"
                },
                "creationdate": {
                    "$ref": "#/definitions/pgtype.Timestamptz"
                },
                "currentplayerturn": {
                    "type": "integer"
                },
                "cutgamecardid": {
                    "type": "integer"
                },
                "deckid": {
                    "type": "integer"
                },
                "elorangemax": {
                    "type": "integer"
                },
                "elorangemin": {
                    "type": "integer"
                },
                "gamestate": {
                    "$ref": "#/definitions/queries.Gamestate"
                },
                "id": {
                    "type": "integer"
                },
                "playerids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.Player"
                    }
                },
                "privatematch": {
                    "type": "boolean"
                },
                "turnpasstimestamps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pgtype.Timestamptz"
                    }
                }
            }
        },
        "vo.HandModifier": {
            "type": "object",
            "properties": {
                "cardIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "matchId": {
                    "type": "integer"
                },
                "playerId": {
                    "type": "integer"
                }
            }
        },
        "vo.JoinMatchReq": {
            "type": "object",
            "properties": {
                "matchId": {
                    "type": "integer"
                },
                "playerId": {
                    "type": "integer"
                }
            }
        },
        "vo.MatchDetailsResponse": {
            "type": "object",
            "properties": {
                "gameState": {
                    "$ref": "#/definitions/queries.Gamestate"
                },
                "matchId": {
                    "type": "integer"
                },
                "playerId": {
                    "type": "integer"
                }
            }
        },
        "vo.MatchRequirements": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "integer"
                },
                "eloRangeMax": {
                    "type": "integer"
                },
                "eloRangeMin": {
                    "type": "integer"
                },
                "isPrivate": {
                    "type": "boolean"
                },
                "playerId": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.2",
	Host:             "localhost:1323",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "cribbage server",
	Description:      "cribbage rest server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
