CREATE TYPE CardState AS ENUM (
  'Deck',
  'Hand',
  'Play',
  'Kitty'
);

CREATE TABLE IF NOT EXISTS matchCards (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cardId integer NOT NULL,
  origOwner integer,
  currOwner integer,
  state CardState NOT NULL
);