CREATE TYPE GameState AS ENUM (
  'NewGameState',
  'JoinGameState',
  'WaitingState',
  'MatchReady',
  'DealState',
  'DiscardState',
  'CutState',
  'PlayState',
  'OpponentState',
  'KittyState',
  'GameWonState',
  'GameLostState',
  'MaxGameState'
);

CREATE TABLE IF NOT EXISTS gameplayCards (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cardId integer NOT NULL,
  origOwner integer,
  currOwner integer,
  state GameState NOT NULL
);