CREATE TABLE IF NOT EXISTS deck_matchCard (
  deckId integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT fk_deck
    FOREIGN KEY(deckId) 
      REFERENCES deck(id),
  matchCardId integer NOT NULL,
  CONSTRAINT fk_matchCard
    FOREIGN KEY(matchCardId) 
      REFERENCES matchCard(id)
);