CREATE TABLE IF NOT EXISTS match_player (
  matchId integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT fk_match
    FOREIGN KEY(matchId) 
      REFERENCES match(id),
  playerId integer NOT NULL,
  CONSTRAINT fk_player
    FOREIGN KEY(playerId) 
      REFERENCES player(id)
);