CREATE TYPE CardSuit AS ENUM (
  'Spades',
  'Clubs',
  'Hearts',
  'Diamonds'
);

CREATE TYPE CardValue AS ENUM (
  'Ace',
  'Two',
  'Three',
  'Four',
  'Five',
  'Six',
  'Seven',
  'Eight',
  'Nine',
  'Ten',
  'Jack',
  'Queen',
  'King',
  'Joker'
);

CREATE TABLE IF NOT EXISTS card (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  value CardValue NOT NULL,
  suit CardSuit NOT NULL,
  art varchar(500) NOT NULL
);