CREATE TYPE CardState AS ENUM (
  'Deck',
  'Hand',
  'Play',
  'Kitty'
);

CREATE TABLE IF NOT EXISTS matchCards (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  CONSTRAINT fk_match
    FOREIGN KEY(match_id) 
      REFERENCES match(id),
  cardId integer NOT NULL,
  origOwner integer,
  currOwner integer,
  state CardState NOT NULL
);