CREATE TABLE IF NOT EXISTS gameplayCards (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cardId integer NOT NULL,
  origOwner numeric NOT NULL,
  currOwner numeric NOT NULL,
  state integer NOT NULL
);