CREATE TABLE IF NOT EXISTS items (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(500) NOT NULL,
  cost numeric NOT NULL,
  weight numeric NOT NULL,
  unit varchar(10) NOT NULL,
  barcode varchar(500) NOT NULL,
  storeId varchar(500) NOT NULL,
  storeName varchar(500) NOT NULL,
  storeNeighborhood varchar(500) NOT NULL,
  tags int8[] NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);