CREATE TABLE IF NOT EXISTS player (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  accountId integer NOT NULL,
  play integer [] NOT NULL,
  hand integer [] NOT NULL,
  kitty integer [] NOT NULL,
  score integer NOT NULL,
  isReady boolean NOT NULL,
  art varchar(500) NOT NULL
);