CREATE TABLE IF NOT EXISTS player (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hand integer [] NOT NULL,
  kitty integer [] NOT NULL,
  score integer NOT NULL,
  art varchar(500) NOT NULL
);