CREATE TABLE IF NOT EXISTS match (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  lobbyId numeric NOT NULL,
  cardsInPlay integer [],
  cutGameCardId integer,
  currentPlayerTurn integer NOT NULL,
  turnPassTimestamps varchar(256) [],
  art varchar(256) NOT NULL
);