CREATE TABLE IF NOT EXISTS chatMessage (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sender int NOT NULL,
  message varchar(500) NOT NULL,
  timestamp timestamptz NOT NULL DEFAULT now()
);