CREATE TABLE IF NOT EXISTS relations (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  barcode varchar(500) NOT NULL,
  relatedBarcodes text[] NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);