CREATE TABLE IF NOT EXISTS matchHistory (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  MatchId integer NOT NULL,
  MatchCompletetionDate timestamptz NOT NULL DEFAULT now(),
  Winners integer [] NOT NULL,
  Losers integer [] NOT NULL
);